# Generated by Django 3.1 on 2022-09-01 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webdriver', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OJProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oj_name', models.CharField(db_index=True, max_length=255)),
                ('oj_problem_code', models.CharField(db_index=True, default=None, max_length=255)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('time_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('memory_limit', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('duration_seconds', models.IntegerField()),
                ('slug', models.SlugField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('show_greetings', models.BooleanField(default=False)),
                ('greetings', tinymce.models.HTMLField(blank=True, null=True)),
                ('is_leaderboard_enabled', models.BooleanField(default=False)),
                ('is_public_leaderboard_enabled', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('FULL_CODING', 'Full Coding')], default='FULL_CODING', max_length=255)),
                ('priority_index', models.IntegerField(default=0)),
                ('enable_team_contest', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default='arnold.ardianto.aa@gmail.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('members', models.ManyToManyField(db_index=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamForProblemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problemset')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.team')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemsetEligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(db_index=True, default=True)),
                ('problemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problemset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OJSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('oj_name', models.CharField(db_index=True, max_length=255)),
                ('oj_problem_code', models.CharField(db_index=True, default='', max_length=255)),
                ('verdict', models.CharField(default='Pending', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=255, null=True)),
                ('source_code', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('oj_login_account_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webdriver.ojloginaccountinfo')),
                ('problemset', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problemset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OJProblemForContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_index', models.IntegerField(default=100)),
                ('oj_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ojproblem')),
                ('problemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problemset')),
            ],
        ),
    ]
