# Generated by Django 3.1 on 2022-11-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojsubmission',
            name='enable_partial_scoring',
            field=models.BooleanField(default=False),
        ),
    ]
