# Generated by Django 3.1 on 2022-11-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20221110_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojsubmission',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
