# Generated by Django 3.1 on 2022-11-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_ojproblem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='enable_partial_scoring',
            field=models.BooleanField(default=False),
        ),
    ]
